#!/bin/bash
#FounzyWeb server  &&&& DEBIAN
#SUDO                 2022              SERVERHU.EU

url=$1
basename=$(basename $url)
filename=${basename%.*}
echo $filename

clone() {
    rm -rf /data/* && \
    cd /tmp/sudo && \
    rm -rf * && \
    git clone $url && \
    mv /tmp/sudo/$filename/* /data
}

clone