#!/bin/bash
#FounzyWeb-PHP server  &&&& Ubuntu
#SUDO                 2022              SERVERHU.EU

url=$1
basename=$(basename $url)
filename=${basename%.*}
echo $filename

gitshit() {
GIT_TERMINAL_PROMPT=0
echo $GIT_TERMINAL_PROMPT
}

clone() {
    cd /tmp/sudo
    rm -rf *

    if ! (GIT_TERMINAL_PROMPT=0 git clone $url) then
        echo "Hibás link"
        exit 1
    else
        echo "Success"
        rm -rf /data/*
        mv /tmp/sudo/$filename/* /data
    fi

}

gitshit
clone