#!/bin/bash
#FounzyWeb-PHP server  &&&& Ubuntu
#SUDO                 2022              SERVERHU.EU
st () {
    /usr/sbin/nginx
}
phpst() {
    cd /etc/init.d
    ./php8.0-fpm start
}

normal_startup() {
    echo "A mappa nem üres" && \
    st
    phpst
}

emptystart() {
    echo "A mappa üres" && \
    mv /FounzyCONF/index.php /data && \
    st
    phpst
}

if find /data -mindepth 1 -maxdepth 1 | read; then
   normal_startup
else
   emptystart
fi